# Generated by Django 4.2 on 2024-03-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='electrodomesticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrodomestico', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('compra', models.IntegerField()),
                ('cliente', models.CharField(max_length=30)),
                ('DNI', models.IntegerField()),
            ],
        ),
    ]
